### ISSUE TITLE
Spark DCOS Java 1.8

### ISSUE THREAD

**Issue by besil** [mesosphere/dcos-spark#11]
Hi,

I'm not sure to post this here, so please point me to the correct location in case.

We are having trouble deploying Spark jobs written in Java 1.8 on our DCOS cluster.

The job fails with the exception `Unsupported major.minor version 52.0`, because Spark on DCOS is running Java 1.7, while our code is written in Java 1.8.

Any plan to migrate to 1.8? Is there any workaround to get it working, apart from rewriting our code in 1.7 style (Spark without lambdas is very cumbersome...)?

Thank you very much

**Comment by tnachen** [comment]
I see, sorry about this I compiled the Spark binaries with JDK 1.7. I think we just need to produce new docker image and then switch the image to use the JDK 1.8 one. Do you have a Spark 1.4.1 + JDK 1.8 + Hadoop 2.6 prebuilt binaries somewhere available?

**Comment by besil** [comment]
Hi Timothy,

We extended the Mesosphere dockerfile in order to use Spark along with
Java1.8.
You can find the Dockerfile definition pasted above:

/*** Dockerfile ***/

FROM mesosphere/spark:1.4.0-rc4-hdfs

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:webupd8team/java
RUN apt-get update

# Auto-accept the Oracle JDK license
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select
true | sudo /usr/bin/debconf-set-selections

RUN apt-get install -y oracle-java8-installer

ENV JAVA_HOME=/usr/lib/jvm/java-8-oracle
RUN rm -rf /usr/lib/jvm/default-java && ln -s /usr/lib/jvm/java-8-oracle
/usr/lib/jvm/default-java
RUN rm -rf /usr/lib/jvm/java-7-openjdk-amd64 && ln -s
/usr/lib/jvm/java-8-oracle /usr/lib/jvm/java-7-openjdk-amd64

/** Dockerfile End **/

2015-08-11 1:48 GMT+02:00 Timothy Chen <notifications@github.com>:

**Comment by tnachen** [comment]
@besil The problem with just extending our image is that the Spark jars are built with JDK 1.7 in the previous image, so once you get JDK 1.8 installed and using that you're still not going to be compatible.

What essential you have to do is to build Spark from source with JDK 1.8 
(basically make-distribution.sh -Phadoop2.4 with java 8), and you can follow the steps here:

https://github.com/tnachen/spark/tree/dockerfile/mesos_docker

**Comment by larsburgess** [comment]
+1 for JDK 1.8 support. Is it in the roadmap for the near future or should we customize our spark installs with a docker image that has JDK 1.8 as per above instructions?

**Comment by mgummelt** [comment]
The latest version of dcos-spark runs Java 1.8
