### ISSUE TITLE
Missing resource on aws ?

### ISSUE THREAD

**Issue by jdassonvil** [mesosphere/dcos-spark#16]
Hi,

I'm trying to install dcos spark but the installation failed at the last step when it tries to fetch resources from aws.

The following command return an HTTP 403 error:
wget http://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark-1.5.0-bin-2.4.0-28fb11ce902ca.tgz

Could you please check if the resource is still available ?

By the way the spark version is harcoded in the script `env.sh`, is there any good reason for that ?

**Comment by ssk2** [comment]
Hey @jdassonvil - how are you trying to install it? Via `dcos package install --cli spark`?

**Comment by ssk2** [comment]
Ah, you're using the repo instructions?

**Comment by jdassonvil** [comment]
The repo instruction, are they outdated ?

**Comment by ssk2** [comment]
They could be improved! It looks like that file is in the right place though.

**Comment by ssk2** [comment]
Okay - please try again - I've altered the permissions.

**Comment by jdassonvil** [comment]
It's good now ! Thank you for your reactivity.

**Comment by ssk2** [comment]
No worries! Closing for now, let us know if there are any other issues.
