### ISSUE TITLE
Can't install spark package 1.5

### ISSUE THREAD

**Issue by jbrisbin** [mesosphere/dcos-spark#19]
I'm getting the same error trying to install Spark 1.5 as the user in #18 The stacktrace is the same.

We can't use 1.6 due to application requirements. Is there a workaround?

**Comment by mgummelt** [comment]
The MemoryError?

The wheel file before 1.6 is quite large, since it includes the Spark distribution.  It looks like pip might be trying to decode that in memory.  Are you on a machine with a small amount of memory?  It looks like maybe you're on an EC2 machine?

Easiest workaround is to use a larger memory machine.

You could also try to manually download the wheel and then install it into your Spark environment at ~/.dcos/subcommands/spark/env

**Comment by jbrisbin** [comment]
How do I do that unattended? I'm using automated builds on docker hub to get a custom image with the packages I need in addition to spark.

**Comment by travisbhartwell** [comment]
I'm working with @jbrisbin on this.

@mgummelt I'm new to how the dcos-cli works.  I believe I read somewhere that it uses Python virtualenvs.  I looked at what is in ~/.dcos/subcommands/spark/env on a higher memory machine that successfully installed dcos-spark and it looked like more than just unzipping the contents of the .whl file.

What do I need to do to install it in that location?  I tried this following, but it did not work:
```
cd /tmp
curl -O https://s3.amazonaws.com/downloads.mesosphere.io/dcos/spark/dcos_spark-0.4.0_spark_1.5.0_multi_roles_v2_bin_2.4.0-py2.py3-none-any.whl
cd ~/.dcos/subcommands
mkdir spark
cd spark
virtualenv env
source env/bin/activate
python -m wheel install /tmp/dcos_spark-0.4.0_spark_1.5.0_multi_roles_v2_bin_2.4.0-py2.py3-none-any.whl
deactivate
```

After doing this, I ran `dcos`, hoping to see spark listed as one of the subcommands, but it was not.  What else do I need to do?

**Comment by mgummelt** [comment]
DCOS creates other files in that subcommands directory, and won't recognize the command unless those files exist.  You could install a version that works (like 1.6), uninstall the builtin dcos-spark wheel, and install the old version.  Then the files should be there.

Another workaround is to avoid "dcos spark run" altogether, and just use "spark-submit".  That's what it's running under the hood.  You'll need to read the "dcos-spark" code and see how it constructs the "spark-submit" command.  All it really does is set the docker image to run the job in, and points spark-submit at our cluster dispatcher, which is at <dcos-url>/service/sparkcli

**Comment by travisbhartwell** [comment]
FYI, this is what I had to do to get it working:

```
cd /tmp
curl -O https://s3.amazonaws.com/downloads.mesosphere.io/dcos/spark/dcos_spark-0.4.0_spark_1.5.0_multi_roles_v2_bin_2.4.0-py2.py3-none-any.whl
cd ~/.dcos/subcommands
mkdir spark
cd spark
virtualenv env
source env/bin/activate
pip install --use-wheel /tmp/dcos_spark-0.4.0_spark_1.5.0_multi_roles_v2_bin_2.4.0-py2.py3-none-any.whl
deactivate
```

I then copied ~/.dcos/subcommands/spark/{package.json,source,version} from a working install into place and it works as expected.

**Comment by mgummelt** [comment]
Since this is a memory issue, not a dcos-spark bug, I'm closing this.

**Comment by jbrisbin** [comment]
We have a fix for this. I'll try to get it updated tomorrow.
