### ISSUE TITLE
Add a license file to the repo

### ISSUE THREAD

**Issue by mbrukman** [mesosphere/dcos-spark#2]
Please add a LICENSE file to the repo so that it's clear under what license it is being provided.

**Comment by tnachen** [comment]
Added now!

**Comment by mbrukman** [comment]
Thanks for working on this!

Unfortunately, [this](https://github.com/mesosphere/dcos-spark/commit/2167cdbc812a3eb8204b4af2efd11b5885580e99) is the short-form license header (suitable for comments at the top of a file) and is not a complete, self-contained license: it actually doesn't list any terms or conditions of the license, just tells you where you can find it elsewhere.

The complete license is [this entire file](http://www.apache.org/licenses/LICENSE-2.0.txt) which is what you want to save as the `LICENSE` file in your repo.

**Comment by tnachen** [comment]
HI Misha,

Sounds good I just updated it.

**Comment by mbrukman** [comment]
Thanks, @tnachen! Would you mind doing the same for other Mesosphere repos, e.g., [dcos-openvpn](https://github.com/mesosphere/dcos-openvpn), [dcos-cli](https://github.com/mesosphere/dcos-cli), [dcos-swarm](https://github.com/mesosphere/dcos-swarm), [dcos-hdfs](https://github.com/mesosphere/dcos-hdfs), and others as well?

**Comment by tnachen** [comment]
I can only add to dcos-swarm, please file a ticket for the others.

Thanks!

Tim

**Comment by ssk2** [comment]
@mbrukman - we're on it for the repos you mentioned!
