### ISSUE TITLE
How is supposed to run Thrift server?

### ISSUE THREAD

**Issue by CyborTronik** [mesosphere/dcos-spark#37]
Sorry, but I didn't found how to do that in official documentations.
And its a bit strange while the the submit job is via `dcos cli`

**Comment by mgummelt** [comment]
The docker image shipped with the DC/OS spark universe package contains a full spark distribution, including ./spark-submit.  Though we don't compile with thrift support, so it may not work.  You can always compile your own spark distribution and just use it against DC/OS as you would any mesos cluster.

**Comment by CyborTronik** [comment]
That makes DC/OS almost useless by philosophy. Nice just for 'hello world' programs(if so, considering the instability of system itself).
Thanks

**Comment by mgummelt** [comment]
We'll consider adding thrift to our default distribution.
