### ISSUE TITLE
Spark CLI run command issue

### ISSUE THREAD

**Issue by AndriiOmelianenko** [mesosphere/dcos-spark#6]
I'm trying to run test spark job (SparkPi example) and receive this error:
```
$ dcos spark run --submit-args='--class org.apache.spark.examples.SparkPi http://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark-examples_2.10-1.4.0-SNAPSHOT.jar 10'
Traceback (most recent call last):
  File "/home/centos/.dcos/subcommands/spark/env/bin/dcos-spark", line 11, in <module>
    sys.exit(main())
  File "/home/centos/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/cli.py", line 63, in main
    return run_spark_job(args)
  File "/home/centos/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/cli.py", line 30, in run_spark_job
    return spark_submit.submit_job(master(), args['--submit-args'], docker_image)
  File "/home/centos/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 44, in submit_job
    props = props + ["-Dspark.mesos.executor.docker.image=" + docker_image]
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
Can you help me please? 
Am I using correct parameters due to last commits into master (https://github.com/mesosphere/dcos-spark/commit/bfd4a6efb57fe3759004854015b54d33fb0cf96a)?

**Comment by besil** [comment]
it seems that in `cli.run_spark_job(args)` docker_image is None
`docker_image = args.get('--docker-image', constants.spark_mesos_image)` doesn't get the correct value. 

this is a script bug, a fast workaround is adding `--docker-image mesosphere/spark:1.4.0-rc4-hdfs` to the dcos command

**Comment by besil** [comment]
it seems that in cli.run_spark_job(args) docker_image is None
docker_image = args.get('--docker-image', constants.spark_mesos_image) doesn't get the correct value.

this is a script bug, a fast workaround is adding --docker-image mesosphere/spark:1.4.0-rc4-hdfs to the dcos command.
I'm creating a pull request

**Comment by elingg** [comment]
Should be fixed. Feel free to reopen if there are still issues.

**Comment by AndriiOmelianenko** [comment]
Issue is fixed, default docker image is working as expected.
Thanks.
